variables:
    IMAGE_NAME: 0siek/private-image-repository
    IMAGE_TAG: python-app-1.0
    DOCKER_TLS_CERTDIR: "/certs" 

stages:
    - test
    - build
    - deploy

run_tests:
    stage: test
    image: python:3.12-slim
    script:
        - echo "RUNNING TESTs (not really)"

build_image:
    stage: build
    image: docker:27.3
    services:
        - docker:27.3-dind
    before_script:
        - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASS}
    script:
        - docker image prune --force --filter='tag=${IMAGE_TAG}'
        - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
        - docker push ${IMAGE_NAME}:${IMAGE_TAG}

deploy:
    stage: deploy
    interruptible: true
    image: docker:27.3
    services:
        - docker:27.3-dind
    only:
        - main
    before_script:
        - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASS}
    script:
        #- docker pull ${IMAGE_NAME}:${IMAGE_TAG}
        #- docker build . -t ${IMAGE_NAME}:${IMAGE_TAG}
        - docker run -d -p 4000:80 ${IMAGE_NAME}:${IMAGE_TAG}